### ISSUE TITLE
listenerCreate is not a function

### ISSUE THREAD

**Issue by bonesoul** [guigrpa/storyboard#20]
using node 7

```
const { mainStory, addListener } = require('storyboard');
const consoleListener = require('storyboard/lib/listeners/console');
addListener(consoleListener);
```

```
  var listener = listenerCreate(userConfig, { mainStory: mainStory, hub: hubApiForListeners });
                 ^

TypeError: listenerCreate is not a function
    at addListener (E:\Coding\buharmetre\node_modules\storyboard\lib\gral\hub.js:55:18)
    at Object.<anonymous> (E:\Coding\buharmetre\src\app.js:24:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:418:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:533:3
```

**Comment by guigrpa** [comment]
If you're consuming the library from a CommonJS module (i.e. via `require`), you need to add this:

```
const consoleListener = require('storyboard/lib/listeners/console').default;
```

Pls let me know if that helps.

**Comment by guigrpa** [comment]
Closed due to inactivity (reopen if necessary).
